package com.example.noteapp.service;

import com.example.noteapp.dto.NoteDTO;
import com.example.noteapp.mapper.AbstractConverter;
import com.example.noteapp.model.Note;
import com.example.noteapp.model.Tag;
import com.example.noteapp.repository.NoteRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
public class NoteService {

    private final AbstractConverter converter;
    private final NoteRepository noteRepository;
    private final TagService tagService;

    public NoteService(AbstractConverter converter, NoteRepository noteRepository, TagService tagService) {
        this.converter = converter;
        this.noteRepository = noteRepository;
        this.tagService = tagService;
    }

    public List<Note> getAllNotes() {
        return noteRepository.findAll();
    }

    public Note getNoteById(UUID id) {
        return noteRepository.findById(id).orElseThrow(() -> new RuntimeException("Note not found"));
    }

    public NoteDTO saveNote(NoteDTO noteDTO) {
        Note note = converter.toEntity(noteDTO);
        noteRepository.save(note);
        return converter.toDTO(note);
    }

    public void deleteNoteById(UUID id) {
        noteRepository.deleteById(id);
    }
    public Note addTagsToNote(UUID noteId, List<String> tagNames, boolean isAutoGenerated) {
        Note note = noteRepository.findById(noteId).orElseThrow(() -> new RuntimeException("Note not found"));

        for (String tagName : tagNames) {
            Tag tag = tagService.createTag(tagName, isAutoGenerated);
            note.getTags().add(tag);
        }

        return noteRepository.save(note);
    }
}
