package com.example.noteapp.service;

import com.example.noteapp.model.Tag;
import com.example.noteapp.repository.TagRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
public class TagService {

    private final TagRepository tagRepository;

    public TagService(TagRepository tagRepository) {
        this.tagRepository = tagRepository;
    }

    public List<Tag> getAllTags() {
        return tagRepository.findAll();
    }

    public Tag createTag(String name, boolean isAutoGenerated) {
        Optional<Tag> existingTag = tagRepository.findByName(name);
        if (existingTag.isPresent()) {
            return existingTag.get(); // Возвращаем существующий тег
        }
        Tag tag = new Tag();
        tag.setName(name);
        tag.setAutoGenerated(isAutoGenerated);
        return tagRepository.save(tag);
    }

    public void deleteTagById(UUID id) {
        tagRepository.deleteById(id);
    }
}

