spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: noteapp
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: a0bc7b7381a84739be01111f12d9447e
            client-secret: c0701b6fad07403c8a8b6f9e99874e1f
            scope:
              - login
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/yandex"  # "{baseUrl}/login/oauth2/code/yandex"
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
    password:
      encoder-strength: 12
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB


  datasource:
    url: jdbc:postgresql://localhost:5432/note_app_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
  security:
    user:
      name: admin
      password: admin123
      enabled: false
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: none
      tracking-modes: cookie
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 250MB
  mvc:
    dispatcherServlet:
      throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: NoteApp API
    description: API для управления заметками и анализа данных
    version: 1.0.0

integration:
  api-url: "https://api.example.com/analyze"

telegram:
  bot:
    token: "7645020182:AAESVweSGS_n7ZbxFx3NNRE4YmrvZ6HsXvg"
    username: "AltaBrain_bot"
logging:
  threshold:
    console: INFO
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        hibernate: ERROR
      apache:
        tomcat: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
file:
  storage-path: /Users/savki/uploaded/uploaded-files
audio:
  storage-path: /Users/savki/uploaded/uploaded-audios
  storage-public-path: /files
  storage-directory: E:/uploaded
open-graph-data:
  enabled: true

jwt:
  secret: e0ccMN3fqRE30HcE6Me2xnGF88e1xVrGwNndNzTd
  expiration:
    access: 3600000  # 1 ???
    refresh: 86400000  # 1 ????

