spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: noteapp
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            scope:
              - login
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}/login/oauth2/code/yandex"
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
    password:
      encoder-strength: 12
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}
  security:
    user:
      name: admin
      password: admin123
      enabled: false
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: none
      tracking-modes: cookie
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  mvc:
    dispatcherServlet:
      throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: NoteApp API
    description: API для управления заметками и анализа данных
    version: 1.0.0

integration:
  api-url: ${AI_URL}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    enabled: ${TELEGRAM_BOT_ENABLED}  # по умолчанию true
logging:
  threshold:
    console: INFO
  level:
    org:
      springframework:
        web: info
        hibernate: info
        security: warn
      apache:
        tomcat: info
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              BasicBinder: info
file:
  storage-path: ${FILE_STORAGE_PATH}
audio:
  storage-path: ${AUDIO_STORAGE_PATH}
  storage-public-path: /files
  storage-directory: ${STORAGE_DIRECTORY}
open-graph-data:
  enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${EXPIRATION_TOKEN_ACCESS}
    refresh: ${EXPIRATION_TOKEN_REFRESH}

backend:
  url: ${BASE_URL}
uploaded:
    path: ${UPLOAD_PATH}


